version: '3'

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_USER=devstracker
      - POSTGRES_DB=devstracker