server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devstracker
    username: devstracker
    password: qwe123
logging:
  level:
    root: WARN
    com.crionuke.devstracker: DEBUG