server:
  port: 10001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devstracker
    username: devstracker
    password: qwe123
logging:
  level:
    root: WARN
    com.crionuke.devstracker: DEBUG
devsTracker:
  freeTrackersLimit: 2
  maxTrackersLimit: 4
api:
  revenueCat:
    secretKey: FPWcTjJxfXPvrBNdFfkvYgCqBsggmJyG